server:
  port: 8089
spring:
  application:
    name: cart-service
  redis:
    host: 172.16.36.164
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
ly:
  jwt:
    pubKeyPath: /Users/lxf/Desktop/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN