server:
  port: 8083

spring:
  application:
    name: item-service
  datasource:
      url: jdbc:mysql://172.16.36.164:3306/leyou?characterEncoding=UTF-8
      username: root
      password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka
    instance:
        lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
        lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
        prefer-ip-address: true
        ip-address: 127.0.0.1
        instance-id: ${spring.application.name}:${server.port}
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl